/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import static fatec.poo.model.Pessoa.validaCPF;
import javax.swing.JOptionPane;

/**
 *
 * @author zaps
 */
public class GuiAluno extends javax.swing.JFrame {

    private Conexao conexao = null;
    private DaoAluno daoAluno = null;
    private Aluno aluno = null;
    private Pessoa pessoa = null;

    /**
     * Creates new form GuiAluno
     */
    public GuiAluno() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCPFaluno = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEndreco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        formattedTxtCpf = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        cbxSexo = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        lblDataNasc = new javax.swing.JLabel();
        lblEscolaridade = new javax.swing.JLabel();
        formattedTxtDataNascimento = new javax.swing.JFormattedTextField();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        lblTelResidencial = new javax.swing.JLabel();
        formattedTxtTelefoneResidencial = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        formattedTxtCelular = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();

        setTitle("Cadastrar aluno");
        setName("frmAluno"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCPFaluno.setText("CPF");

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        lblEndreco.setText("Endereço");

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        lblRG.setText("RG");

        lblEmail.setText("Email");

        try {
            formattedTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNome.setEnabled(false);

        txtEndereco.setEnabled(false);

        txtBairro.setEnabled(false);

        txtCidade.setEnabled(false);

        txtRg.setEnabled(false);

        txtEmail.setEnabled(false);

        cbxSexo.setEnabled(false);

        lblEstadoCivil.setText("Estado civil");

        cbxEstadoCivil.setEnabled(false);

        lblDataNasc.setText("Data de nascimento");

        lblEscolaridade.setText("Escolaridade");

        try {
            formattedTxtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTxtDataNascimento.setEnabled(false);

        cbxEscolaridade.setEnabled(false);

        lblNumero.setText("Nº");

        txtNumero.setEnabled(false);

        lblCEP.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setEnabled(false);

        lblTelResidencial.setText("Telefone Residencial");

        try {
            formattedTxtTelefoneResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTxtTelefoneResidencial.setEnabled(false);

        lblCelular.setText("Celular");

        try {
            formattedTxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTxtCelular.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado");

        cbxEstado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(lblCPFaluno)
                    .addComponent(lblNome)
                    .addComponent(lblSexo)
                    .addComponent(lblEndreco)
                    .addComponent(lblBairro)
                    .addComponent(lblCidade)
                    .addComponent(lblRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblEstadoCivil)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEndereco)
                                .addComponent(txtRg)
                                .addComponent(txtEmail)
                                .addComponent(formattedTxtCpf)
                                .addComponent(txtNome))
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEscolaridade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataNasc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCEP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelResidencial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCelular, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEscolaridade, 0, 171, Short.MAX_VALUE)
                            .addComponent(formattedTxtDataNascimento)
                            .addComponent(txtNumero)
                            .addComponent(txtCep)
                            .addComponent(formattedTxtTelefoneResidencial)
                            .addComponent(formattedTxtCelular))
                        .addGap(29, 29, 29))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBairro, txtCidade, txtEmail, txtRg});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFaluno)
                    .addComponent(formattedTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNasc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formattedTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolaridade)
                    .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndreco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCEP)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCidade)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelResidencial)
                        .addComponent(formattedTxtTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRG)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(formattedTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxEscolaridade, cbxEstadoCivil, cbxSexo, formattedTxtCelular, formattedTxtCpf, formattedTxtDataNascimento, formattedTxtTelefoneResidencial, txtBairro, txtCep, txtCidade, txtEmail, txtEndereco, txtNome, txtNumero, txtRg});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        lblEstado.getAccessibleContext().setAccessibleDescription("");
        cbxEstado.getAccessibleContext().setAccessibleName("");
        cbxEstado.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD1813031", "BD1813031");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");
        daoAluno = new DaoAluno(conexao.conectar());

        //Sexo
        String[] sexos = new String[3];
        sexos[0] = "M";
        sexos[1] = "F";
        sexos[2] = "Outro";

        for (String sexo : sexos) {
            cbxSexo.addItem(sexo);
        }

        String[] estados = new String[26];
        estados[0] = "AC";
        estados[1] = "AL";
        estados[2] = "AP";
        estados[3] = "AM";
        estados[4] = "BA";
        estados[5] = "CE";
        estados[6] = "DF";
        estados[7] = "ES";
        estados[8] = "GO";
        estados[9] = "MA";
        estados[10] = "MS";
        estados[11] = "MT";
        estados[12] = "MG";
        estados[13] = "PA";
        estados[14] = "PB";
        estados[15] = "PR";
        estados[16] = "PE";
        estados[17] = "PI";
        estados[18] = "RJ";
        estados[19] = "RN";
        estados[20] = "RS";
        estados[21] = "RO";
        estados[22] = "RR";
        estados[22] = "SC";
        estados[23] = "SP";
        estados[24] = "SE";
        estados[25] = "TO";

        for (String estado : estados) {
            cbxEstado.addItem(estado);
        }

        String[] estadoCivil = new String[5];
        estadoCivil[0] = "Solteiro";
        estadoCivil[1] = "Casado";
        estadoCivil[2] = "Separado";
        estadoCivil[3] = "Divorciado";
        estadoCivil[4] = "Viúvo";

        for (String civil : estadoCivil) {
            cbxEstadoCivil.addItem(civil);
        }

        String[] escolaridade = new String[7];
        escolaridade[0] = "Lê e escreve";
        escolaridade[1] = "Ensino Fundamental Incompleto";
        escolaridade[2] = "Ensino Fundamental Completo";
        escolaridade[3] = "Ensino Médio Incompleto";
        escolaridade[4] = "Ensino Médio Completo";
        escolaridade[5] = "Ensino Superior Incompleto";
        escolaridade[6] = "Ensino Superior Completo";

    }//GEN-LAST:event_formWindowOpened

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
            daoAluno.excluir(aluno);

            // Limpa os campos
            this.limparCampos();

            //CombosBox
            cbxEscolaridade.setEnabled(false);                                  //Escolaridade
            cbxEstado.setEnabled(false);                                        //Estado
            cbxEstadoCivil.setEnabled(false);                                   //Estado Civil
            cbxSexo.setEnabled(false);                                          //Sexo
            //Formatted
            formattedTxtCpf.setEnabled(true);                                   //CPF
            formattedTxtDataNascimento.setEnabled(true);                        //Data Nasc
            //Txts
            txtNome.setEnabled(false);                                          //Nome
            txtBairro.setEnabled(false);                                        //Bairro
            formattedTxtCelular.setEnabled(false);                              //Celular
            txtCep.setEnabled(false);                                           //CEP
            txtCidade.setEnabled(false);                                        //Cidade
            txtEmail.setEnabled(false);                                         //Email
            txtEndereco.setEnabled(false);                                      //Endereço
            txtNumero.setEnabled(false);                                        //Número
            txtRg.setEnabled(false);
            formattedTxtTelefoneResidencial.setEnabled(false);

            //Botões
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        //Obtendo dados
        String cpf;
        cpf = formattedTxtCpf.getText();

        if (validaCPF(cpf) == false) {
            JOptionPane.showMessageDialog(null, "CPF Inválido! Por favor digite"
                    + "um CPF válido! ");
            formattedTxtCpf.setText("");
            btnConsultar.setEnabled(true);
        } else {
            aluno = new Aluno(formattedTxtCpf.getText(),
                    txtNome.getText());
            aluno.setBairro(txtBairro.getText());
            aluno.setCEP(txtCep.getText());
            aluno.setCelular(formattedTxtCelular.getText());
            aluno.setCidade(txtCidade.getText());
            aluno.setDataNasc(formattedTxtDataNascimento.getText());
            aluno.setEmail(txtEmail.getText());
            aluno.setEndereco(txtEndereco.getText());
            aluno.setEscolaridade(cbxEscolaridade.getSelectedItem().toString());
            aluno.setEstado(cbxEstado.getSelectedItem().toString());
            aluno.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
            aluno.setNumero(Integer.parseInt(txtNumero.getText()));
            aluno.setRG(txtRg.getText());
            aluno.setSexo(cbxSexo.getSelectedItem().toString());
            aluno.setTelefone(formattedTxtTelefoneResidencial.getText());
            daoAluno.inserir(aluno);

            // Limpando os campos
            this.limparCampos();

            // Habilintandos txts
            formattedTxtCpf.setEnabled(true);
            txtNome.setEnabled(false);
            txtBairro.setEnabled(false);
            formattedTxtCelular.setEnabled(false);
            txtCep.setEnabled(false);
            txtCidade.setEnabled(false);
            txtEmail.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtRg.setEnabled(false);
            formattedTxtTelefoneResidencial.setEnabled(false);

            //CombosBox
            cbxEscolaridade.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            cbxSexo.setEnabled(false);

            //Botões
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            // Obtendo alterações
            aluno.setBairro(txtBairro.getText());                               //Bairro
            aluno.setCEP(txtCep.getText());                                     //CEP
            aluno.setCelular(formattedTxtCelular.getText());                    //Celular
            aluno.setCidade(txtCidade.getText());                               //Cidade
            aluno.setDataNasc(formattedTxtDataNascimento.getText());            //Data Nasciento
            aluno.setEmail(txtEmail.getText());                                 //E-mail
            aluno.setEndereco(txtEndereco.getText());                           //Endereço
            aluno.setEscolaridade(cbxEscolaridade.getSelectedItem().toString());//Escolaridade
            aluno.setEstado(cbxEstado.getSelectedItem().toString());            //Estado
            aluno.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());  //Estado Civil
            aluno.setNome(txtNome.getText());                                   //Nome
            aluno.setNumero(Integer.parseInt(txtNumero.getText()));             //Numero
            aluno.setRG(txtRg.getText());                                       //RG
            aluno.setSexo(cbxSexo.getSelectedItem().toString());                //Sexo
            aluno.setTelefone(formattedTxtTelefoneResidencial.getText());       //Telefone Residencial
            //Chamando o método Alterar da classe DaoAluno
            daoAluno.alterar(aluno);
        }

        // Limpando os Componentes
        this.limparCampos();

        //CombosBox
        cbxEscolaridade.setEnabled(false);
        cbxEstado.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxSexo.setEnabled(false);
        //Formatteds
        formattedTxtCelular.setEnabled(false);
        formattedTxtCpf.setEnabled(true);
        formattedTxtDataNascimento.setEnabled(true);
        formattedTxtTelefoneResidencial.setEnabled(false);
        //Txts
        txtNome.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEmail.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRg.setEnabled(false);

        //Botões
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        aluno = null;
        String cpf = formattedTxtCpf.getText();

        if (validaCPF(cpf) == false) {
            JOptionPane.showMessageDialog(null, "CPF Inválido! Por favor digite"
                    + "um CPF válido! ");
            formattedTxtCpf.setText("");
            btnConsultar.setEnabled(true);
        } else {
            //Chamando o método Consultar da classe DaoAluno
            aluno = daoAluno.consultar(formattedTxtCpf.getText());

            if (aluno == null) {
                //CombosBox
                cbxEstado.setEnabled(true);                                     //Estado
                cbxEscolaridade.setEnabled(true);                               //Escolaridade
                cbxEstadoCivil.setEnabled(true);                                //Estado Civil
                cbxSexo.setEnabled(true);                                       //Sexo
                //FormattedTXT
                formattedTxtCelular.setEnabled(true);                           //Celular
                formattedTxtCpf.setEnabled(false);                              //CPF
                formattedTxtDataNascimento.setEnabled(true);                    //Data Nascimento
                formattedTxtTelefoneResidencial.setEnabled(true);               //Tel Residencial
                //Txts
                txtBairro.setEnabled(true);                                     //Bairro
                txtCep.setEnabled(true);                                        //CEP
                txtCidade.setEnabled(true);                                     //Cidade
                txtEmail.setEnabled(true);                                      //Email
                txtEndereco.setEnabled(true);                                   //Endereço
                txtNome.setEnabled(true);                                       //Nome
                txtNumero.setEnabled(true);                                     //Numero
                txtRg.setEnabled(true);                                         //RG

                //Foco
                txtNome.requestFocus();

                //Botões
                btnConsultar.setEnabled(false);                                 //Consultar
                btnInserir.setEnabled(true);                                    //Inserir
                btnAlterar.setEnabled(false);                                   //Alterar
                btnExcluir.setEnabled(false);                                   //Excluir
            } else {
                // Preenchendo dados
                //Combos Box

                cbxEscolaridade.setSelectedItem(aluno.getEscolaridade());       //Escolaridade
                cbxEstado.setSelectedItem(aluno.getEstado());                   //Estado
                cbxSexo.setSelectedItem(aluno.getSexo());                       //Sexo
                //Formatteds(Sem CPF)
                formattedTxtCelular.setText(aluno.getCelular());                //Celular
                formattedTxtDataNascimento.setText(aluno.getDataNasc());        //Data Nasc
                formattedTxtTelefoneResidencial.setText(aluno.getTelefone());   //Tel Residencial

                //Txts
                txtBairro.setText(aluno.getBairro());                           //Bairro
                txtCep.setText(aluno.getCEP());                                 //CEP
                txtCidade.setText(aluno.getCidade());                           //Cidade
                txtEmail.setText(aluno.getEmail());                             //Email
                txtEndereco.setText(aluno.getEndereco());                       //Endereço
                txtNome.setText(aluno.getNome());                               //Nome
                txtNumero.setText(String.valueOf(aluno.getNumero()));           //Numero
                txtRg.setText(aluno.getRG());                                   //RG

                /*Desabilitando Campos
                - Formatteds */
                formattedTxtCelular.setEnabled(true);                           //Celular
                formattedTxtCpf.setEnabled(false);                              //CPF
                formattedTxtDataNascimento.setEnabled(true);                    //Data Nasc
                formattedTxtTelefoneResidencial.setEnabled(true);               //Tel Residencial
                //Txts
                txtNome.setEnabled(true);                                       //Nome
                txtBairro.setEnabled(true);                                     //Bairro
                txtCep.setEnabled(true);                                        //CEP
                txtCidade.setEnabled(true);                                     //Cidade
                txtEmail.setEnabled(true);                                      //E-mail
                txtEndereco.setEnabled(true);                                   //Endereço
                txtNumero.setEnabled(true);                                     //Número
                txtRg.setEnabled(true);                                         //RG

                //CombosBox
                cbxEstado.setEnabled(true);                                     //Estado
                cbxEscolaridade.setEnabled(true);                               //Escolaridade
                cbxEstadoCivil.setEnabled(true);                                //Estado Civil
                cbxSexo.setEnabled(true);                                       //Sexo

                //Foco
                txtNome.requestFocus();

                //Botões
                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    public void limparCampos() {
        formattedTxtCpf.setText("");
        txtNome.setText("");
        formattedTxtCpf.requestFocus();
        txtBairro.setText("");
        formattedTxtCelular.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtRg.setText("");
        formattedTxtTelefoneResidencial.setText("");

        // Deselecionando combobox
        cbxEscolaridade.setSelectedItem("");
        cbxEstadoCivil.setSelectedItem("");
        cbxSexo.setSelectedItem("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JFormattedTextField formattedTxtCelular;
    private javax.swing.JFormattedTextField formattedTxtCpf;
    private javax.swing.JFormattedTextField formattedTxtDataNascimento;
    private javax.swing.JFormattedTextField formattedTxtTelefoneResidencial;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPFaluno;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndreco;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelResidencial;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtRg;
    // End of variables declaration//GEN-END:variables
}
